<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SMS_MD.Entities\SMS_MD.Entities.csproj" />
    <ProjectReference Include="..\SMS_MD.Models\SMS_MD.Models.csproj" />
  </ItemGroup>

</Project>
