// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SMS_MD.Entities.Views;

public partial class SMSMDContext : DbContext
{
    public SMSMDContext(DbContextOptions<SMSMDContext> options)
        : base(options)
    {
    }

    public virtual DbSet<VwUserPersonLink> VwUserPersonLinks { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<VwUserPersonLink>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("vw_UserPersonLinks");

            entity.Property(e => e.Email).HasMaxLength(256);
            entity.Property(e => e.Roles).HasMaxLength(4000);
            entity.Property(e => e.RollNumber).HasMaxLength(30);
            entity.Property(e => e.StaffCode).HasMaxLength(20);
            entity.Property(e => e.Username)
                .IsRequired()
                .HasMaxLength(100);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}