// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMS_MD.Entities.Models;

public partial class Assessment
{
    public int AssessmentId { get; set; }

    public int SectionId { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public decimal MaxPoints { get; set; }

    public decimal? WeightPercent { get; set; }

    public DateTime? DueDate { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime? UpdatedAtUtc { get; set; }

    public int? CreatedByUserId { get; set; }

    public int? UpdatedByUserId { get; set; }

    public byte[] RowVersion { get; set; }

    public virtual AppUser CreatedByUser { get; set; }

    public virtual ICollection<Grade> Grades { get; set; } = new List<Grade>();

    public virtual ClassSection Section { get; set; }

    public virtual AppUser UpdatedByUser { get; set; }
}